### ISSUE TITLE
Blotter does not scale when in its own window

### ISSUE THREAD

**Issue by tdeheurles** [AdaptiveConsulting/ReactiveTraderCloud#201]
![image](https://cloud.githubusercontent.com/assets/9496645/13600238/dc38b154-e527-11e5-949d-fce88c238dd3.png)

Not sure it is relevant, just to notice.

**Comment by LeeCampbell** [comment]
Might be related to #216

**Comment by KeithWoods** [comment]
This should be fixed via the new styling work, adding the appropriate label.

**Comment by fdore** [comment]
Blotter is now taking the full space when opening in a new window. The blotter still wont scale when resizing the window though as the resize handler is still attached to the parent window.

**Comment by KeithWoods** [comment]
@DimitarChristoff were you looking at this?

**Comment by DimitarChristoff** [comment]
yes, it's now fixed in react-dimensions and blocked by https://github.com/digidem/react-dimensions/pull/22 being merged in. we can temporarily stick our own dimensions.jsx until the PR goes through
